backend:
  name: github
  repo: partnerandpartners/holly-how # Path to your Github repository
  branch: master # Branch to update
  publish_mode: editorial_workflow

media_folder: "images/"

collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "base"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", required: false, widget: "image"}
      - {label: "Tags", name: "tags", widget: "categories"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "home" # Used in routes, e.g. /admin/collections/blog
    label: "Home" # Used in the UI
    files:
      - name: "home" # Used in routes, e.g. /admin/collections/blog
        label: "Home" # Used in the UI
        file: "index.md"
        fields: # The fields for each document, usually in front matter
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Body", name: "body", widget: "hidden"}
          - {label: "Main Title", name: "title", widget: "string"}
          - {label: "Main Introduction", name: "introduction", widget: "text"}
          - {label: "Main Image", name: "main_image", widget: "image", required: false}
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Section Title", name: "section_title", widget: "string"}
              - {label: "Section Text", name: "section_text", widget: "text"}
              - {label: "Section Image", name: "section_image", widget: "image", required: false}
              - {label: "Section Selection", name: "section_select", widget: "select", options: ["Left", "Right"]}

  - name: "page" # Used in routes, e.g. /admin/collections/blog
    label: "Page" # Used in the UI
    files:
      - name: "Services"
        label: "Services page"
        file: "_pages/services.md"
        fields: # The fields for each document, usually in front matter
          - {label: "Layout", name: "layout", widget: "hidden", default: "base"}
          - {label: "Body", name: "body", widget: "hidden"}
          - {label: "Main Title", name: "title", widget: "string"}
          - {label: "Main Introduction", name: "introduction", widget: "text"}
          - {label: "Main Image", name: "main_image", widget: "image", required: false}
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Section Title", name: "section_title", widget: "string"}
              - {label: "Section Text", name: "section_text", widget: "text"}
              - {label: "Section Image", name: "section_image", widget: "image", required: false}
              - {label: "Section Selection", name: "section_select", widget: "select", options: ["Left", "Right"]}
      - name: "Programs"
        label: "Programs page"
        file: "_pages/programs.md"
        fields: # The fields for each document, usually in front matter
          - {label: "Layout", name: "layout", widget: "hidden", default: "base"}
          - {label: "Body", name: "body", widget: "hidden"}
          - {label: "Main Title", name: "title", widget: "string"}
          - {label: "Main Introduction", name: "introduction", widget: "text"}
          - {label: "Main Image", name: "main_image", widget: "image", required: false}
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Section Title", name: "section_title", widget: "string"}
              - {label: "Section Text", name: "section_text", widget: "text"}
              - {label: "Section Image", name: "section_image", widget: "image", required: false}
              - {label: "Section Selection", name: "section_select", widget: "select", options: ["Left", "Right"]}

  - name: "clients" # Used in routes, e.g. /admin/collections/blog
    label: "Clients" # Used in the UI
    files:
      - name: "client-list"
        label: "Client List"
        file: "_data/clients.json"
        - fields: # The fields for each document, usually in front matter
          widget: "list"
          fields:
            - {label: "Client Name", name: "client_name", widget: "string"}
            - {label: "Client Link", name: "client_link", widget: "string",required: false}
